name: Gradle Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
          unzip -d /opt/gradle gradle-7.5.1-bin.zip
        env:
          GRADLE_HOME: /opt/gradle/gradle-7.5.1
          PATH: ${{env.GRADLE_HOME}}/bin:$PATH

      - name: Build and Test
        run: ./gradlew test
